1.	Write a Python Program to Add Two Matrices?

In [7]:
import numpy as np

a=np.matrix([[1,2,3,4],[4,5,6,7]])
b=np.matrix([[11,21,31,41],[41,51,61,71]])

c=a+b
print(c)

[[12 23 34 45]
 [45 56 67 78]]


In [8]:
import numpy as np

#matrix addition in python using numpy
rows = int(input("Enter the Number of rows : " ))
column = int(input("Enter the Number of Columns: "))

#accept the first matix
print("Enter the elements of First Matrix:")
matrix_a= [[int(input()) for i in range(column)] for i in range(rows)]
print("First Matrix is: ")
for n in matrix_a:
    print(n)

#convert the first matrix into numpy array
matrix_a = np.array(matrix_a)

#accept the second matix
print("Enter the elements of Second Matrix:")
matrix_b= [[int(input()) for i in range(column)] for i in range(rows)]
for n in matrix_b:
    print(n)
    
#convert the second matrix into numpy array
matrix_b = np.array(matrix_b)    

#add two matrices in python using numpy
result = np.add(matrix_a, matrix_b)

print("The Sum of Above two Matrices is : ")
for r in result:
    print(r)

Enter the Number of rows : 2
Enter the Number of Columns: 2
Enter the elements of First Matrix:
1
2
3
5
First Matrix is: 
[1, 2]
[3, 5]
Enter the elements of Second Matrix:
3
5
6
4
[3, 5]
[6, 4]
The Sum of Above two Matrices is : 
[4 7]
[9 9]


2.	Write a Python Program to Multiply Two Matrices?

In [9]:
# Program to multiply two matrices using list comprehension

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [12]:
import numpy as np

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

[[ 36 -12]
 [ -1   2]]


3.	Write a Python Program to Transpose a Matrix?

In [13]:
import numpy as np

A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

[[ 1  2  3]
 [ 1  1 -3]]


In [14]:
''' Program to transpose a matrix using list comprehension'''

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]

for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]


4.	Write a Python Program to Sort Words in Alphabetic Order?

In [15]:
# Program to sort alphabetically the words form a string provided by the user

my_str = "Hello this Is an Example With cased letters"

# To take input from the user
#my_str = input("Enter a string: ")

# breakdown the string into a list of words
words = [word.lower() for word in my_str.split()]

# sort the list
words.sort()

# display the sorted words

print("The sorted words are:")
for word in words:
   print(word)

The sorted words are:
an
cased
example
hello
is
letters
this
with


5.	Write a Python Program to Remove Punctuation From a String?

In [16]:
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, he said ---and went."

# To take input from the user
# my_str = input("Enter a string: ")

# remove punctuation from the string
no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)


Hello he said and went
